# Generated by Django 2.1.1 on 2018-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_textfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfiles',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
