# Generated by Django 2.1.1 on 2018-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_textfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
