# Generated by Django 2.1.1 on 2018-10-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('origin', models.TextField()),
                ('scientific_name', models.TextField(null=True)),
                ('rank', models.CharField(max_length=20, null=True)),
                ('hybrid', models.TextField(null=True)),
                ('cultivar', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('telugu', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TextFiles',
        ),
    ]
